# Valeurs Helm utilisées pour installer Traefik dans kind (dev local)
# Commande : helm install traefik traefik/traefik --namespace traefik --create-namespace -f traefik-kind-values.yaml

deployment:
  kind: DaemonSet

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443

service:
  type: ClusterIP
